name: cdk-testing-project-deployment
run-name: ${{ github.actor }} cdktf testing project
on:
  push:
    branches: [ main ]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g bats
      - run: bats -v | ls -al | npm install

  build:
    name: setup aws credentials
    runs-on: ubuntu-latest
    steps:
      - name: GitCheckout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
#      - name: Checkout
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.POC_ACCESS_KEY }}
#          aws-secret-access-key: ${{ secrets.POC_SECRET_ASSESS_KEY }}
#          aws-region: us-east-2
#      - run: aws sts get-caller-identity
#      - name: List S3 Buckets
#        run: |
#          aws s3 ls
      - name: Deploy CDKTF Template
        run: |
          ls -al 

